[
  {
    name: "Ora",
    startDate: "7/2021",
    endDate: "11/2021",
    title: "Full-Stack Developer",
    label: "Work as remotely, Contract",
    data: [
      "Build a Ora’s company website",
      "Used the React.js for build the website",
      "Pixel-Perfect website comfortable with desktop and mobile",
      "Implement an email registration feature",
      "Used i18n for multi-language support",
    ],
  },
  {
    name: "Tokemak",
    startDate: "1/2021",
    endDate: "7/2021",
    title: "Front-End Developer",
    label: "Work as remotely, Contract",
    data: [
      "Build a Tokemak’s degenesis event website using React.js",
      "Implement the wallet connection and web3 stuff like commit funds",
      "Write and Deploy the Smart Contracts",
      "Modify Bridge between Ethereum vs Onomy",
    ],
  },
  {
    name: "Badger Finance",
    startDate: "7/2020",
    endDate: "1/2021",
    title: "Front-End Developer",
    label: "Work as remotely, Contract",
    data: [
      "Build a v2 Badger Finance homepage using React.js",
      "Pixel-perfect website comfortable with desktop and mobile",
      "Implement the smooth animation and modern design",
    ],
  },
  {
    name: "SimpleNight",
    startDate: "2/2020",
    endDate: "7/2020",
    title: "Front-End Developer",
    label: "Work as remotely, Contract",
    data: [
      "Refactoring current PHP Laravel website to React.js",
      "Configuring project to React.js, Redux, Redux-Thunk, Material-UI",
      "Making transitions and animations using CSS",
    ],
  },
  {
    name: "Codera",
    startDate: "8/2019",
    endDate: "2/2020",
    title: "Full-Stack Developer",
    label: "Work as remotely, Contract",
    data: [
      "Develop the Groji mobile app using Expo(React-Native), Node.js, GraphQL, PostgreSQL",
      "Used GraphQL query, mutation, subscription for API",
      "Used sequelize ORM npm module for connecting PostgreSQL in node.js",
      "Make a chat in the mobile app that support sending msg, emoji and media, typing status, read status…",
      "Feed functionality that posted by other users and sort them with proper algorithm",
      "Several profile feature like twitter and handling subscription response timing.",
    ],
  },
  {
    name: "Nova Pursuits",
    startDate: "3/2019",
    endDate: "8/2019",
    title: "React-Native Developer",
    label: "Work as remotely, Contract",
    data: [
      "Build a IOT related Tellicare Mobile app using React-Native",
      "Connect with Wi-Fi, Lan, heater machine for get status and control the heater",
      "Customize and use Particle Module for IOT stuff",
      "Zepplin app for design tool",
    ],
  },
  {
    name: "Vision-e",
    startDate: "10/2015",
    endDate: "3/2019",
    title: "React-Native Developer",
    label: "Work as remotely, Fulltime",
    data: [
      "Develop several mobile apps using React-Native, published to app store and google play store",
      "Checking the app’s security real-time using several platforms and improve using top minification of the code, encrypt database",
      "Build Native components and make bridge module for using in React-Native",
      "Integrating with Salesforce, Google APIs, Microsoft Dynamics, Outlook…",
      "Carry out quality assurance tests to discover errors and optimize usability",
      "Used i18n for multi language support",
      "OCR technology for scanning business card image ",
      "Google Language API for getting the meaning of scanned words",
      "Worked on many image processing work like rotating, cropping, drawing",
    ],
  },
];
